In [49]:
import pandas as pd

df = pd.read_csv("../data/raw/UCI_Credit_Card.csv")
print(df.shape)
df.head()

(30000, 25)

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default.payment.next.month
0,1,20000.0,2,2,1,24,2,2,-1,-1,...,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0,1
1,2,120000.0,2,2,2,26,-1,2,0,0,...,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0,1
2,3,90000.0,2,2,2,34,0,0,0,0,...,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0,0
3,4,50000.0,2,2,1,37,0,0,0,0,...,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0,0
4,5,50000.0,1,2,1,57,-1,0,-1,0,...,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0,0

In [50]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 25 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   ID                          30000 non-null  int64
 1   LIMIT_BAL                   30000 non-null  float64
 2   SEX                         30000 non-null  int64
 3   EDUCATION                   30000 non-null  int64
 4   MARRIAGE                    30000 non-null  int64
 5   AGE                         30000 non-null  int64
 6   PAY_0                       30000 non-null  int64
 7   PAY_2                       30000 non-null  int64
 8   PAY_3                       30000 non-null  int64
 9   PAY_4                       30000 non-null  int64
 10  PAY_5                       30000 non-null  int64
 11  PAY_6                       30000 non-null  int64
 12  BILL_AMT1                   30000 non-null  float64
 13  BILL_AMT2                   30000 non-null  float64
 14  BILL_AMT3                   30000 non-null  float64
 15  BILL_AMT4                   30000 non-null  float64
 16  BILL_AMT5                   30000 non-null  float64
 17  BILL_AMT6                   30000 non-null  float64
 18  PAY_AMT1                    30000 non-null  float64
 19  PAY_AMT2                    30000 non-null  float64
 20  PAY_AMT3                    30000 non-null  float64
 21  PAY_AMT4                    30000 non-null  float64
 22  PAY_AMT5                    30000 non-null  float64
 23  PAY_AMT6                    30000 non-null  float64
 24  default.payment.next.month  30000 non-null  int64
dtypes: float64(13), int64(12)
memory usage: 5.7 MB

In [51]:
df.describe()

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default.payment.next.month
count,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,...,30000.000000,30000.000000,30000.000000,30000.000000,3.000000e+04,30000.00000,30000.000000,30000.000000,30000.000000,30000.000000
mean,15000.500000,167484.322667,1.603733,1.853133,1.551867,35.485500,-0.016700,-0.133767,-0.166200,-0.220667,...,43262.948967,40311.400967,38871.760400,5663.580500,5.921163e+03,5225.68150,4826.076867,4799.387633,5215.502567,0.221200
std,8660.398374,129747.661567,0.489129,0.790349,0.521970,9.217904,1.123802,1.197186,1.196868,1.169139,...,64332.856134,60797.155770,59554.107537,16563.280354,2.304087e+04,17606.96147,15666.159744,15278.305679,17777.465775,0.415062
min,1.000000,10000.000000,1.000000,0.000000,0.000000,21.000000,-2.000000,-2.000000,-2.000000,-2.000000,...,-170000.000000,-81334.000000,-339603.000000,0.000000,0.000000e+00,0.00000,0.000000,0.000000,0.000000,0.000000
25%,7500.750000,50000.000000,1.000000,1.000000,1.000000,28.000000,-1.000000,-1.000000,-1.000000,-1.000000,...,2326.750000,1763.000000,1256.000000,1000.000000,8.330000e+02,390.00000,296.000000,252.500000,117.750000,0.000000
50%,15000.500000,140000.000000,2.000000,2.000000,2.000000,34.000000,0.000000,0.000000,0.000000,0.000000,...,19052.000000,18104.500000,17071.000000,2100.000000,2.009000e+03,1800.00000,1500.000000,1500.000000,1500.000000,0.000000
75%,22500.250000,240000.000000,2.000000,2.000000,2.000000,41.000000,0.000000,0.000000,0.000000,0.000000,...,54506.000000,50190.500000,49198.250000,5006.000000,5.000000e+03,4505.00000,4013.250000,4031.500000,4000.000000,0.000000
max,30000.000000,1000000.000000,2.000000,6.000000,3.000000,79.000000,8.000000,8.000000,8.000000,8.000000,...,891586.000000,927171.000000,961664.000000,873552.000000,1.684259e+06,896040.00000,621000.000000,426529.000000,528666.000000,1.000000

In [52]:
df.isna().sum()

ID                            0
LIMIT_BAL                     0
SEX                           0
EDUCATION                     0
MARRIAGE                      0
AGE                           0
PAY_0                         0
PAY_2                         0
PAY_3                         0
PAY_4                         0
PAY_5                         0
PAY_6                         0
BILL_AMT1                     0
BILL_AMT2                     0
BILL_AMT3                     0
BILL_AMT4                     0
BILL_AMT5                     0
BILL_AMT6                     0
PAY_AMT1                      0
PAY_AMT2                      0
PAY_AMT3                      0
PAY_AMT4                      0
PAY_AMT5                      0
PAY_AMT6                      0
default.payment.next.month    0
dtype: int64

In [53]:
df["default.payment.next.month"].value_counts(normalize= True)

default.payment.next.month
0    0.7788
1    0.2212
Name: proportion, dtype: float64

In [54]:
df["EDUCATION"].value_counts()

EDUCATION
2    14030
1    10585
3     4917
5      280
4      123
6       51
0       14
Name: count, dtype: int64

In [55]:
df["MARRIAGE"].value_counts()

MARRIAGE
2    15964
1    13659
3      323
0       54
Name: count, dtype: int64

In [56]:
df["SEX"].value_counts()

SEX
2    18112
1    11888
Name: count, dtype: int64

In [57]:
df =df.rename(columns={"default.payment.next.month": "default", "PAY_0":"PAY_1"})
df = df.drop(columns=["ID"])
df["EDUCATION"]=df["EDUCATION"].replace({0:4, 5:4, 6:4})
df["MARRIAGE"]=df["MARRIAGE"].replace({0 : 3})

In [58]:
print(df.shape)
print(df.columns.tolist())
print(df["EDUCATION"].value_counts())
print(df["MARRIAGE"].value_counts())

(30000, 24)
['LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_1', 'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2', 'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1', 'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6', 'default']
EDUCATION
2    14030
1    10585
3     4917
4      468
Name: count, dtype: int64
MARRIAGE
2    15964
1    13659
3      377
Name: count, dtype: int64

In [59]:
from sklearn.model_selection import train_test_split
train_df, temp_df = train_test_split(df, test_size=0.3 , stratify=df["default"], random_state=42)
val_df, test_df = train_test_split(temp_df, test_size=0.5, stratify= temp_df["default"], random_state= 42)

In [60]:
for name, part in [("train", train_df), ("val", val_df), ("test", test_df)]:
    print(name, part.shape, round(part["default"].mean(), 3))

train (21000, 24) 0.221
val (4500, 24) 0.221
test (4500, 24) 0.221

In [61]:
X_train = train_df.drop(columns=["default"])
y_train = train_df["default"]
X_val = val_df.drop(columns=["default"])
y_val = val_df["default"]

In [62]:
print(X_train.shape)
print(y_train.shape)

(21000, 23)
(21000,)

In [63]:
train_df.info()

<class 'pandas.DataFrame'>
Index: 21000 entries, 11018 to 27126
Data columns (total 24 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   LIMIT_BAL  21000 non-null  float64
 1   SEX        21000 non-null  int64
 2   EDUCATION  21000 non-null  int64
 3   MARRIAGE   21000 non-null  int64
 4   AGE        21000 non-null  int64
 5   PAY_1      21000 non-null  int64
 6   PAY_2      21000 non-null  int64
 7   PAY_3      21000 non-null  int64
 8   PAY_4      21000 non-null  int64
 9   PAY_5      21000 non-null  int64
 10  PAY_6      21000 non-null  int64
 11  BILL_AMT1  21000 non-null  float64
 12  BILL_AMT2  21000 non-null  float64
 13  BILL_AMT3  21000 non-null  float64
 14  BILL_AMT4  21000 non-null  float64
 15  BILL_AMT5  21000 non-null  float64
 16  BILL_AMT6  21000 non-null  float64
 17  PAY_AMT1   21000 non-null  float64
 18  PAY_AMT2   21000 non-null  float64
 19  PAY_AMT3   21000 non-null  float64
 20  PAY_AMT4   21000 non-null  float64
 21  PAY_AMT5   21000 non-null  float64
 22  PAY_AMT6   21000 non-null  float64
 23  default    21000 non-null  int64
dtypes: float64(13), int64(11)
memory usage: 4.0 MB

In [64]:
categorical_cols = ["SEX","EDUCATION","MARRIAGE"]
numeric_cols = X_train.columns.drop(categorical_cols).tolist()

In [65]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder

scaler = StandardScaler()
encoder = OneHotEncoder(handle_unknown = "ignore")

In [66]:
from sklearn.compose import ColumnTransformer

numeric_step = ("num" , scaler , numeric_cols)
categorical_step = ("cat" , encoder, categorical_cols)

preprocessor = ColumnTransformer([numeric_step, categorical_step])

In [67]:
preprocessor.fit(X_train)

X_train_ready = preprocessor.transform(X_train)
print(X_train_ready.shape)

(21000, 29)

In [68]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

In [69]:
log_reg = LogisticRegression(max_iter=1000)

In [70]:
model= Pipeline([("preprocessor", preprocessor),("classifier", log_reg)])

In [71]:
model

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['LIMIT_BAL', 'AGE', 'PAY_1',
                                                   'PAY_2', 'PAY_3', 'PAY_4',
                                                   'PAY_5', 'PAY_6',
                                                   'BILL_AMT1', 'BILL_AMT2',
                                                   'BILL_AMT3', 'BILL_AMT4',
                                                   'BILL_AMT5', 'BILL_AMT6',
                                                   'PAY_AMT1', 'PAY_AMT2',
                                                   'PAY_AMT3', 'PAY_AMT4',
                                                   'PAY_AMT5', 'PAY_AMT6']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['SEX', 'EDUCATION',
                                                   'MARRIAGE'])])),
                ('classifier', LogisticRegression(max_iter=1000))])

In [72]:
model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['LIMIT_BAL', 'AGE', 'PAY_1',
                                                   'PAY_2', 'PAY_3', 'PAY_4',
                                                   'PAY_5', 'PAY_6',
                                                   'BILL_AMT1', 'BILL_AMT2',
                                                   'BILL_AMT3', 'BILL_AMT4',
                                                   'BILL_AMT5', 'BILL_AMT6',
                                                   'PAY_AMT1', 'PAY_AMT2',
                                                   'PAY_AMT3', 'PAY_AMT4',
                                                   'PAY_AMT5', 'PAY_AMT6']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['SEX', 'EDUCATION',
                                                   'MARRIAGE'])])),
                ('classifier', LogisticRegression(max_iter=1000))])

In [73]:
y_val_pred = model.predict(X_val)

In [74]:
y_val_pred

array([0, 0, 0, ..., 0, 0, 0], shape=(4500,))

In [75]:
y_val_pred.sum()

np.int64(348)

In [76]:
y_val.sum()

np.int64(995)

In [77]:
from sklearn.metrics import confusion_matrix
conf_mat = confusion_matrix(y_val, y_val_pred)

In [78]:
conf_mat

array([[3398,  107],
       [ 754,  241]])

In [79]:
from sklearn.metrics import recall_score, precision_score
print(recall_score(y_val,y_val_pred), precision_score(y_val, y_val_pred))

0.2422110552763819 0.6925287356321839

In [80]:
from sklearn.metrics import f1_score 
print(f1_score(y_val, y_val_pred))

0.35889798957557706

In [81]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_val, y_val_pred))

0.8086666666666666

In [82]:
y_val_proba = model.predict_proba(X_val)

In [83]:
y_val_proba

array([[0.78385079, 0.21614921],
       [0.86463924, 0.13536076],
       [0.93533879, 0.06466121],
       ...,
       [0.89181835, 0.10818165],
       [0.77828626, 0.22171374],
       [0.53906219, 0.46093781]], shape=(4500, 2))

In [84]:
y_val_proba_default = y_val_proba[:, 1]

In [85]:
y_val_proba_default

array([0.21614921, 0.13536076, 0.06466121, ..., 0.10818165, 0.22171374,
       0.46093781], shape=(4500,))

In [86]:
from sklearn.metrics import roc_auc_score
print(roc_auc_score(y_val, y_val_proba_default))

0.714281536068359

In [87]:
from sklearn.metrics import average_precision_score
print(average_precision_score(y_val, y_val_proba_default))

0.5031982850535316

In [108]:
results = {
    "Model": ["Logistic Regression","Random Forest", "Random Forest max_depth=10"],
    "ROC-AUC": [0.70,0.76,0.77],
    "PR-AUC" :[0.50, 0.53,0.55],
    "Precision": [0.69,0.65,0.68],
    "Recall": [0.24,0.35,0.35],
    "F1": [0.36,0.46,0.46],
}
results_df = pd.DataFrame(results)

In [109]:
results_df

                        Model  ROC-AUC  PR-AUC  Precision  Recall    F1
0         Logistic Regression     0.70    0.50       0.69    0.24  0.36
1               Random Forest     0.76    0.53       0.65    0.35  0.46
2  Random Forest max_depth=10     0.77    0.55       0.68    0.35  0.46

In [102]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(random_state=42)

In [92]:
rf_model = Pipeline([("preprocessor",preprocessor),("classifier",rf)])

In [93]:
rf_model

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['LIMIT_BAL', 'AGE', 'PAY_1',
                                                   'PAY_2', 'PAY_3', 'PAY_4',
                                                   'PAY_5', 'PAY_6',
                                                   'BILL_AMT1', 'BILL_AMT2',
                                                   'BILL_AMT3', 'BILL_AMT4',
                                                   'BILL_AMT5', 'BILL_AMT6',
                                                   'PAY_AMT1', 'PAY_AMT2',
                                                   'PAY_AMT3', 'PAY_AMT4',
                                                   'PAY_AMT5', 'PAY_AMT6']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['SEX', 'EDUCATION',
                                                   'MARRIAGE'])])),
                ('classifier', RandomForestClassifier(random_state=42))])

In [94]:
rf_model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['LIMIT_BAL', 'AGE', 'PAY_1',
                                                   'PAY_2', 'PAY_3', 'PAY_4',
                                                   'PAY_5', 'PAY_6',
                                                   'BILL_AMT1', 'BILL_AMT2',
                                                   'BILL_AMT3', 'BILL_AMT4',
                                                   'BILL_AMT5', 'BILL_AMT6',
                                                   'PAY_AMT1', 'PAY_AMT2',
                                                   'PAY_AMT3', 'PAY_AMT4',
                                                   'PAY_AMT5', 'PAY_AMT6']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['SEX', 'EDUCATION',
                                                   'MARRIAGE'])])),
                ('classifier', RandomForestClassifier(random_state=42))])

In [95]:
rf_val_pred = rf_model.predict(X_val)
rf_val_proba = rf_model.predict_proba(X_val)[:,1]

In [96]:
rf_conf_mat = confusion_matrix(y_val, rf_val_pred)

In [97]:
rf_conf_mat

array([[3312,  193],
       [ 642,  353]])

In [98]:
print(recall_score(y_val, rf_val_pred), precision_score(y_val, rf_val_pred), f1_score(y_val, rf_val_pred), accuracy_score(y_val, rf_val_pred), roc_auc_score(y_val,rf_val_proba), average_precision_score(y_val,rf_val_proba))

0.35477386934673366 0.6465201465201466 0.4581440622972096 0.8144444444444444 0.757349515050287 0.5311864534535929

In [103]:
trees = rf_model.named_steps["classifier"].estimators_
print(len(trees))
print(trees[0].get_depth())

100
43

In [104]:
rf_train_proba= rf_model.predict_proba(X_train)[:,1]
print(roc_auc_score(y_train, rf_train_proba))

0.999989594436413

In [105]:
rf_10 = RandomForestClassifier(max_depth=10,random_state=42)
rf_10_model = Pipeline([("preprocessor",preprocessor), ("classifier", rf_10)])
rf_10_model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['LIMIT_BAL', 'AGE', 'PAY_1',
                                                   'PAY_2', 'PAY_3', 'PAY_4',
                                                   'PAY_5', 'PAY_6',
                                                   'BILL_AMT1', 'BILL_AMT2',
                                                   'BILL_AMT3', 'BILL_AMT4',
                                                   'BILL_AMT5', 'BILL_AMT6',
                                                   'PAY_AMT1', 'PAY_AMT2',
                                                   'PAY_AMT3', 'PAY_AMT4',
                                                   'PAY_AMT5', 'PAY_AMT6']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['SEX', 'EDUCATION',
                                                   'MARRIAGE'])])),
                ('classifier',
                 RandomForestClassifier(max_depth=10, random_state=42))])

In [106]:
rf_10_train_proba = rf_10_model.predict_proba(X_train)[:,1]
rf_10_val_proba = rf_10_model.predict_proba(X_val)[:,1]
print(roc_auc_score(y_train, rf_10_train_proba),roc_auc_score(y_val, rf_10_val_proba))

0.8624808416857013 0.7735383049340855

In [107]:
rf_10_val_pred = rf_10_model.predict(X_val)
print(recall_score(y_val, rf_10_val_pred),precision_score(y_val, rf_10_val_pred),f1_score(y_val, rf_10_val_pred), average_precision_score(y_val, rf_10_val_proba))

0.3457286432160804 0.6771653543307087 0.4577511643379907 0.5514074096947802